version: '3.9'

services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    restart: always
    volumes:
      - ./docker/db/data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: "./docker/api/Dockerfile"
    ports:
      - 8080:8080
    volumes:
      - ./src/back:/app