"""empty message

Revision ID: 484bef4d68c9
Revises: 980280774dbf
Create Date: 2023-03-13 14:16:17.014184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484bef4d68c9'
down_revision = '980280774dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('tweet_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'tweet_url')
    # ### end Alembic commands ###
