"""empty message

Revision ID: 980280774dbf
Revises: 67e9786a17a9
Create Date: 2023-03-12 14:04:16.983736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '980280774dbf'
down_revision = '67e9786a17a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet_user', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet_user', sa.Column('url', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
