"""empty message

Revision ID: a44cb0651603
Revises: 484bef4d68c9
Create Date: 2023-03-13 14:30:10.806061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44cb0651603'
down_revision = '484bef4d68c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet_user', sa.Column('user_name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'tweet_user', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet_user', type_='unique')
    op.drop_column('tweet_user', 'user_name')
    # ### end Alembic commands ###
